baseURL = "https://rainerchiang.github.io/simpleness/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "simpleness"

title = "Rainer Chiang"
enableInlineShortcodes = true
enableEmoji = true
googleAnalytics = "UA-162425220-2"

[params]
  lazyImage = true
  enableMathJax = false # enable it in Front Matter
  enableReadingTime = true
  favicon = "favicon.ico"
  startyear = "2019"
  description = "A simple and concise hugo theme."
  disqus = "rainerchiang"

[params.valine]
  enable = true
  enableHeaderVisitor = true
  debug = false
  lang = 'en' # zh-CN
  appId = 'CXhRxgF18xcqkQ6ylD56iJC5-MdYXbMMI'
  appKey = 'N0uSp4sS3sxcEbaFgINUHYiy'
  placeholder = 'Say Something......'
  requiredFields = ['nick', 'mail']
  avatar = 'robohash'
  visitor = true

[menu]
  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 1
  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[social]
  github = "https://github.com/RainerChiang"
  rss = "index.xml"

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  # doc: https://gohugo.io/getting-started/configuration-markup#highlight
  # syntax style: https://xyproto.github.io/splash/docs/longer/all.html
  [markup.highlight]
    guessSyntax = true
    hl_Lines = ""
    # lineNoStart = 1
    # lineNos = true
    # lineNumbersInTable = true
    noClasses = true
    style = "monokai" # github, dracula, vim, monokai
    tabWidth = 4